#macro x batch mode


#/vis/open OGL

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi -90 0 deg
/vis/viewer/zoom 0.8


# for drawing the tracks
/vis/scene/add/trajectories

#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
# for drawing the hits, uncomment next line
/vis/scene/add/hits
# (if you prefer refreshing each event, comment out next line)
/vis/scene/endOfEventAction accumulate



/run/verbose 0
/run/dumpRegion 0

/event/verbose 0
/tracking/verbose 0

/control/verbose 0


/run/setCutForAGivenParticle gamma 1 um
/run/setCutForAGivenParticle e- 1 nm
/run/setCutForAGivenParticle e+ 1 um


/run/setCutForAGivenParticle proton 0 um			#vale anche per i neutroni


/gun/particle neutron		# settata nel file PrimaryGenerator, ma modificabile qua (questa viene usata)

/gun/energy .662 MeV 		

/run/beamOn 1000000


